name: Rust workflows

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly

    - name: build project
      run: cargo +nightly build --release
